/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as CasaAntonioARouteImport } from './routes/casa-antonio-a'
import { Route as CasaAntonioBRouteImport } from './routes/casa-antonio-b'
import { Route as DayTripsRouteImport } from './routes/day-trips'
import { Route as NeighborhoodRouteImport } from './routes/neighborhood'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaAntonioARoute = CasaAntonioARouteImport.update({
  id: '/casa-antonio-a',
  path: '/casa-antonio-a',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaAntonioBRoute = CasaAntonioBRouteImport.update({
  id: '/casa-antonio-b',
  path: '/casa-antonio-b',
  getParentRoute: () => rootRouteImport,
} as any)
const DayTripsRoute = DayTripsRouteImport.update({
  id: '/day-trips',
  path: '/day-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodRoute = NeighborhoodRouteImport.update({
  id: '/neighborhood',
  path: '/neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/arrival': typeof ArrivalRoute
  '/casa-antonio-a': typeof CasaAntonioARoute
  '/casa-antonio-b': typeof CasaAntonioBRoute
  '/day-trips': typeof DayTripsRoute
  '/neighborhood': typeof NeighborhoodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/arrival': typeof ArrivalRoute
  '/casa-antonio-a': typeof CasaAntonioARoute
  '/casa-antonio-b': typeof CasaAntonioBRoute
  '/day-trips': typeof DayTripsRoute
  '/neighborhood': typeof NeighborhoodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/arrival': typeof ArrivalRoute
  '/casa-antonio-a': typeof CasaAntonioARoute
  '/casa-antonio-b': typeof CasaAntonioBRoute
  '/day-trips': typeof DayTripsRoute
  '/neighborhood': typeof NeighborhoodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/arrival'
    | '/casa-antonio-a'
    | '/casa-antonio-b'
    | '/day-trips'
    | '/neighborhood'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/arrival'
    | '/casa-antonio-a'
    | '/casa-antonio-b'
    | '/day-trips'
    | '/neighborhood'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/arrival'
    | '/casa-antonio-a'
    | '/casa-antonio-b'
    | '/day-trips'
    | '/neighborhood'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ArrivalRoute: typeof ArrivalRoute
  CasaAntonioARoute: typeof CasaAntonioARoute
  CasaAntonioBRoute: typeof CasaAntonioBRoute
  DayTripsRoute: typeof DayTripsRoute
  NeighborhoodRoute: typeof NeighborhoodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa-antonio-a': {
      id: '/casa-antonio-a'
      path: '/casa-antonio-a'
      fullPath: '/casa-antonio-a'
      preLoaderRoute: typeof CasaAntonioARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa-antonio-b': {
      id: '/casa-antonio-b'
      path: '/casa-antonio-b'
      fullPath: '/casa-antonio-b'
      preLoaderRoute: typeof CasaAntonioBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-trips': {
      id: '/day-trips'
      path: '/day-trips'
      fullPath: '/day-trips'
      preLoaderRoute: typeof DayTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood': {
      id: '/neighborhood'
      path: '/neighborhood'
      fullPath: '/neighborhood'
      preLoaderRoute: typeof NeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ArrivalRoute: ArrivalRoute,
  CasaAntonioARoute: CasaAntonioARoute,
  CasaAntonioBRoute: CasaAntonioBRoute,
  DayTripsRoute: DayTripsRoute,
  NeighborhoodRoute: NeighborhoodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
